receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  awss3:
    s3uploader:
      region: ap-south-1
      s3_bucket: otel-data
      s3_prefix: otel/
      endpoint: s3.ap-south-1.amazonaws.com
    marshaler: otlp_json

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awss3]
    metrics:
      receivers: [otlp]
      exporters: [awss3]
    logs:
      receivers: [otlp]
      exporters: [awss3]
